### ISSUE TITLE
Feature: console comments

### ISSUE THREAD

**Issue by davidmarkclements** [holepunchto/brittle#15]
Support an opt-in that converts console.log/info/error/etc messages into TAP comments. 

Benefits:

* clean tap output
* in concurrent mode, console.log messages will appear as tap comments among the relevant surrounding TAP, instead of being logged out-of-order relative to the TAP output

Enabling:

* `configure({ consoleComments: true }`
* `CC=1 node test.js`
* `brittle --cc test.js`

**Comment by mafintosh** [comment]
We fixed this in v3
