### ISSUE TITLE
after invoking solo in one file, all later tests in other files are skipped

### ISSUE THREAD

**Issue by utanapishtim** [holepunchto/brittle#23]
In testing the gui lib of you know what, we import solo from brittle and apply it with no arguments at the top of the file. All tests in all other files are then skipped. Note: this is when invoking the test file with `brittle`, e.g. `brittle my-test-dir/*.test.js`.

Expected Behavior:
The use of solo in one test file does not effect the behavior of any other test file

**Comment by mafintosh** [comment]
working as intended :)
